server:
  port: 8088

---

spring:
  profiles: default
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/.well-known/jwks.json
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: carmanagement
          uri: http://localhost:8082
          predicates:
            - Path=/dispatchRequests/**, /requestStatuses/**, 
        - id: oauth
          uri: http://localhost:8090
          predicates:
            - Path=/.well-known/**, /auth/**, /users/**
        - id: nginx
          uri: http://localhost:8081
          predicates:
            - Path=/common/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: carmanagement
          uri: http://carmanagement:8080
          predicates:
            - Path=/dispatchRequests/**, /requestStatuses/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
